app = "paris-coder"
primary_region = "cdg"

[experimental]
  entrypoint = ["/bin/sh", "-c", "WIRTUAL_DERP_SERVER_RELAY_URL=\"http://[${FLY_PRIVATE_IP}]:3000\" /opt/coder wsproxy server"]
  auto_rollback = true

[build]
  image = "ghcr.io/coder/coder-preview:main"

[env]
  WIRTUAL_ACCESS_URL = "https://paris.fly.dev.coder.com"
  WIRTUAL_HTTP_ADDRESS = "0.0.0.0:3000"
  WIRTUAL_PRIMARY_ACCESS_URL = "https://dev.coder.com"
  WIRTUAL_WILDCARD_ACCESS_URL = "*--apps.paris.fly.dev.coder.com"
  WIRTUAL_VERBOSE = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# Ref: https://fly.io/docs/reference/configuration/#http_service-concurrency
[http_service.concurrency]
  type = "requests"
  soft_limit = 50
  hard_limit = 100

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
