coder:
  image:
    repo: "${REPO}"
    tag: "pr${PR_NUMBER}"
    pullPolicy: Always
  service:
    type: ClusterIP
  ingress:
    enable: true
    className: traefik
    host: "${PR_HOSTNAME}"
    wildcardHost: "*.${PR_HOSTNAME}"
    tls:
      enable: true
      secretName: "pr${PR_NUMBER}-tls"
      wildcardSecretName: "pr${PR_NUMBER}-tls"
  env:
    - name: "WIRTUAL_ACCESS_URL"
      value: "https://${PR_HOSTNAME}"
    - name: "WIRTUAL_WILDCARD_ACCESS_URL"
      value: "*.${PR_HOSTNAME}"
    - name: "WIRTUAL_EXPERIMENTS"
      value: "${EXPERIMENTS}"
    - name: WIRTUAL_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: "WIRTUAL_OAUTH2_GITHUB_ALLOW_SIGNUPS"
      value: "true"
    - name: "WIRTUAL_OAUTH2_GITHUB_CLIENT_ID"
      value: "${PR_DEPLOYMENTS_GITHUB_OAUTH_CLIENT_ID}"
    - name: "WIRTUAL_OAUTH2_GITHUB_CLIENT_SECRET"
      value: "${PR_DEPLOYMENTS_GITHUB_OAUTH_CLIENT_SECRET}"
    - name: "WIRTUAL_OAUTH2_GITHUB_ALLOWED_ORGS"
      value: "coder"
    - name: "WIRTUAL_DERP_CONFIG_URL"
      value: "https://controlplane.tailscale.com/derpmap/default"
