{
 "title": "CoderV2 Loadtest Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(wirtuald_api_concurrent_requests,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(wirtuald_api_concurrent_requests,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(wirtuald_api_concurrent_requests,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Control Plane Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coder CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"}[$__rate_interval])) ",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Coder memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Coder Network TX/RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (-rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"^coder-(provisioner-)?[a-z0-9]+-[a-z0-9]+$\"}[$__rate_interval]))",
     "legendFormat": "tx {{pod}}"
    },
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"^coder-(provisioner-)?[a-z0-9]+-[a-z0-9]+$\"}[$__rate_interval]))",
     "legendFormat": "rx {{pod}}"
    }
   ]
  },
  {
   "title": "Coder pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (delta(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coder Logs Entries (All Levels)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "+300s",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.project_id",
       "=",
       "v2-loadtest",
       "AND",
       "resource.label.namespace_name",
       "=",
       "coder-big",
       "AND",
       "resource.label.container_name",
       "=",
       "coder",
       "AND",
       "resource.label.cluster_name",
       "=",
       "big",
       "AND",
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.pod_name",
       "!=~",
       "coder-scaletest-.*",
       "AND",
       "resource.label.pod_name",
       "=~",
       "coder-.*",
       "AND",
       "metric.type",
       "=",
       "logging.googleapis.com/log_entry_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "v2-loadtest"
     }
    }
   ]
  },
  {
   "title": "Coder Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "projectId": "v2-loadtest",
     "queryText": "resource.type=\"k8s_container\" AND\nresource.labels.cluster_name=\"big\" AND\nresource.labels.namespace_name=\"coder-big\" AND\nresource.labels.location=\"us-central1-a\" AND\nresource.labels.project_id=\"v2-loadtest\" AND\n(resource.labels.container_name=\"coder\" OR resource.labels.container_name=\"coder-provisionerd\") AND\njsonPayload.message!=\"\" AND\nseverity=\"ERROR\""
    },
    {
     "projectId": "v2-loadtest",
     "queryText": "resource.type=\"k8s_container\" AND\nresource.labels.cluster_name=\"big\" AND\nresource.labels.namespace_name=\"coder-big\" AND\nresource.labels.location=\"us-central1-a\" AND\nresource.labels.project_id=\"v2-loadtest\" AND\ntextPayload=~\"panic:.*\""
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DB CPU Util%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.project_id",
       "=",
       "v2-loadtest",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/cpu/utilization"
      ],
      "groupBys": [ "resource.label.database_id" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "none",
      "projectName": "v2-loadtest"
     }
    }
   ]
  },
  {
   "title": "DB Mem Util%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.project_id",
       "=",
       "v2-loadtest",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/memory/utilization"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "none",
      "projectName": "v2-loadtest"
     }
    }
   ]
  },
  {
   "title": "DB Disk Read I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.project_id",
       "=",
       "v2-loadtest",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/disk/read_ops_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "v2-loadtest"
     }
    }
   ]
  },
  {
   "title": "DB Disk Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.project_id",
       "=",
       "v2-loadtest",
       "AND",
       "metric.type",
       "=",
       "cloudsql.googleapis.com/database/disk/write_ops_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "v2-loadtest"
     }
    }
   ]
  },
  {
   "title": "DB insert/update/delete/return",
   "type": "timeseries",
   "description": "LOGARITHMIC Y AXIS",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "INSERT"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "RETURN"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "FETCH"
    }
   ]
  },
  {
   "title": "DB conns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"active\"} !=0",
     "legendFormat": "active"
    },
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"idle\"} !=0",
     "legendFormat": "idle"
    },
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"idle in transaction\"} != 0",
     "legendFormat": "idle_tx"
    },
    {
     "expr": "pg_stat_activity_count{datname=~\"${cluster}-coder\", cluster=~\"${cluster}\", state=\"disabled\"} != 0",
     "legendFormat": "disabled"
    }
   ]
  },
  {
   "title": "DB TX/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{cluster=~\"$cluster\", datname=\"${cluster}-coder\"}[$__rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "sqlQuerier P95 execution timing",
   "type": "heatmap",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, query) (rate(wirtuald_db_query_latencies_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sqlQuerier execution count",
   "type": "heatmap",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by(le, query) (rate(wirtuald_db_query_latencies_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "API Requests by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(wirtuald_api_requests_processed_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(rate(wirtuald_api_requests_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(wirtuald_api_requests_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "API requests/sec by response, method",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sum by (code,method) (rate(wirtuald_api_requests_processed_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=\"coder\",code!=\"0\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "API Request Latency P95",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(wirtuald_api_request_latencies_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", path=~\"^/api/v2/.*\"}[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "sum by(method, path) (rate(wirtuald_api_request_latencies_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", path=~\"^/api/v2/.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "Workspace Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Scaletest Workspace CPU Usage (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\", resource=\"cpu\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\", container=\"dev\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaletest Workspace Network Usage (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"${cluster}\", namespace=~\"${namespace}\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"${cluster}\", namespace=~\"${namespace}\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\"}[$__rate_interval])) * -1",
     "legendFormat": "tx {{pod}}"
    }
   ]
  },
  {
   "title": "Scaletest Workspace Memory Usage (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\", resource=\"memory\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "avg(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaletest Workspace Network RX/TX errs (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{cluster=~\"${cluster}\", namespace=~\"${namespace}\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\"}[$__rate_interval]))",
     "legendFormat": "rx errs {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{cluster=~\"${cluster}\", namespace=~\"${namespace}\", pod=~\"coder-scaletest-.*-scaletest-.*\", pod!=\"coder-scaletest-runner-scaletest-runner\"}[$__rate_interval])) * -1",
     "legendFormat": "tx errs {{pod}}"
    }
   ]
  },
  { "title": "Workspace Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "Agent Connection RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(wirtuald_agentstats_rx_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(rate(wirtuald_agentstats_tx_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * -1",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Agent Connection Latency P50/95/99",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, wirtuald_agents_connection_latencies_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.95, wirtuald_agents_connection_latencies_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.99, wirtuald_agents_connection_latencies_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Websocket Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (wirtuald_api_concurrent_websockets{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"coder\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (wirtuald_agents_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workspace Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "Workspace Traffic bytes TX/RX",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(wirtuald_scaletest_bytes_written_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) * -1",
     "legendFormat": "tx inside container"
    },
    {
     "expr": "sum by(pod) (rate(wirtuald_scaletest_bytes_read_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "rx inside container"
    },
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval])) * 1",
     "legendFormat": "rx outside container"
    },
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=\"coder-scaletest-workspace-traffic\"}[$__rate_interval])) * -1",
     "legendFormat": "tx outside container"
    }
   ]
  },
  {
   "title": "Workspace Traffic read latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(wirtuald_scaletest_read_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Traffic write latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(wirtuald_scaletest_write_latency_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Traffic Read errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(wirtuald_scaletest_read_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace Traffic Write errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(wirtuald_scaletest_write_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Generation CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 210 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=\"coder-scaletest-runner-scaletest-runner\", container=\"dev\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Generation Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=\"coder-scaletest-runner-scaletest-runner\",container=\"dev\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic generation pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=\"coder-scaletest-runner-scaletest-runner\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scaletest Dashboard Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Dashboard Actions Duration P95",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, action) (rate(wirtuald_scaletest_dashboard_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboard Actions Errors",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(le, action) (rate(wirtuald_scaletest_dashboard_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 238 } },
  {
   "title": "AuthZ Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(wirtuald_authz_authorize_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(wirtuald_authz_authorize_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(wirtuald_authz_authorize_duration_seconds_bucket{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Provisioner Job Timings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(wirtuald_provisionerd_job_timings_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p50-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, pod) (rate(wirtuald_provisionerd_job_timings_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p90-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(wirtuald_provisionerd_job_timings_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p95-{{pod}}"
    }
   ]
  },
  {
   "title": "Total Workspace Builds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 246 },
   "targets": [
    {
     "expr": "sum by(status, pod) (wirtuald_workspace_builds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", workspace_transition=\"START\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent Provisioner Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 246 },
   "targets": [
    {
     "expr": "sum by(status, container) (wirtuald_provisionerd_jobs_current{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status, container) (wirtuald_provisionerd_num_daemons{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"^(coder|provisionerd)$\"})",
     "legendFormat": "builtin_daemons"
    },
    {
     "expr": "sum(kube_pod_container_status_running {cluster=~\"$cluster\", namespace=~\"coder-big\", pod=~\"coder-provisioner-.*\"})",
     "legendFormat": "external_daemons"
    }
   ]
  }
 ]
}